name: PyPI 🐍  Wheel 🎡

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheel
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python: [310]

    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set Up Python
      uses: actions/setup-python@v2

    - name: Build wheels
      run: |
        pip wheel -w wheelhouse . --no-deps

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cubepy-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1

  publish:
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: cubepy-gh-pypi-artifact
        path: wheelhouse/

    - name: Publish a Wheel distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_SECRET }}
        packages_dir: wheelhouse/
