name: CI/CD 📝

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - setup.cfg
      - pyproject.toml
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [37, 38, 39, 310]
        include:
          - os: ubuntu-latest
            platform_id: manylinux_x86_64
          - os: macos-latest
            platform_id: macosx_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set Up Python
      uses: actions/setup-python@v2

    - name: Build wheels
      run: |
        pip wheel -w wheelhouse . --no-deps

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: cubepy-gh-pypi-artifact
        path: wheelhouse/*.whl
        retention-days: 1
