name: PyPI 🐍  Wheel 🎡

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build and Publish wheel to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get history and tags for SCM versioning
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set Up Python
      uses: actions/setup-python@v3

    - name: Build wheels
      run: |
        pip wheel -w wheelhouse . --no-deps

    - name: Publish a Wheel distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.CUBEPY_PYPI_SECRET }}
        packages_dir: wheelhouse/
